"""add all foreingKey

Revision ID: 326449a50ff3
Revises: ce89aacf582f
Create Date: 2024-05-28 23:30:47.125265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326449a50ff3'
down_revision = 'ce89aacf582f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('position_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'company_categories', ['category_id'], ['id'])
        batch_op.create_foreign_key(None, 'individual_positions', ['position_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('position_id')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_by')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
